### ISSUE TITLE
Osx app won't open: libosc.dyld error linking. Library not loaded.

### ISSUE THREAD

**Issue by oishe-muse** [NicoG60/OscMackieControl#1]
Hey,
The binary app for osx won't open. There is an error message that the library isn't linked or loaded properly. However, I can build and run it only inside qt-creator and nowhere else.
Any help with linking the library is appreciated. I just want to run the app without having to use qt-creator. Thanks!

```
Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libosc.dylib
  Referenced from: /Users/USER/*/OscMackieControl.app/Contents/MacOS/OscMackieControl
  Reason: image not found
```

**Comment by NicoG60** [comment]
Hi,Yes, i don't make a deployment script yet, i'm working on it. Un fact i failed the linking between the binary and the lib. It does not search it at the rigth place...Deploying qt app for osx is such a pain for me. I dont use to do it, this is m'y first one. Thanks a lot for (trying) using my app!Le 26 juin 2018 22:51, oishe-muse <notifications@github.com> a écrit :Hey,
The binary app for osx won't open. There is an error message that the library isn't linked or loaded properly. However, I can build and run it only inside qt-creator and nowhere else.
Any help with linking the library is appreciated. I just want to run the app without having to use qt-creator. Thanks!
Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libosc.dylib
  Referenced from: /Users/USER/*/OscMackieControl.app/Contents/MacOS/OscMackieControl
  Reason: image not found

**Comment by NicoG60** [comment]
Ok i've done little modifications on the binary part. I've rebuild it (with newer version of Qt) and deploy it with "macdeployqt" (and copy libosc directly in Frameworks folder)
It seems to work on my computer...
Let me know if it's ok or not! 
All the best

**Comment by aziddy** [comment]
Been having the same problem. Now it works with your new OSX depolyment

merci

**Comment by oishe-muse** [comment]
The new build works fine! Thank you so much!

**Comment by NicoG60** [comment]
Happy to know that! Have fun and let me know if you see some improvement to Be done!
