### ISSUE TITLE
M1 CRASH

### ISSUE THREAD

**Issue by ivan-ef** [NicoG60/OscMackieControl#10]
Sad, but it crashes on Mac m1 after 30 sec of transmitting data.

**Comment by NicoG60** [comment]
Hi, 
as said in the Readme page, that project has been retired before M1 was even a thing. You can have a look at my other project [TouchMCU](https://github.com/NicoG60/TouchMCU) which implements Mackie Control Protocol natively on TouchOSC mkII. That should work with any recent apple product 😊
