### ISSUE TITLE
more info on mackie control protocol

### ISSUE THREAD

**Issue by toneffectory** [NicoG60/OscMackieControl#2]
Hi Nicolas,
In your PDF I read that for some mackie control items you don't have any info on what it supposed to do. In Ableton Live documentation up until v7, there was quite a bit explanation on mackie control protocol. It's not in the current documentation anymore, but here's a link to an excerpt that may provide valuable information. E.g. what assignment does, what rude solo does, etc.
http://eumlab.com/daw-remote-hd/docs/
I found this one especially very helpful: http://eumlab.com/payload/motu_dp.pdf

Not my find btw, but from eumlab, creators of the dawremoteHD ios app.

**Comment by NicoG60** [comment]
Hi!
Sorry for not writing to you earlier! I was pretty busy last year and left that project aside for the time being. Thank you very very much for the few documents you dug out! I've been reading them when you sent them but did not take the time to answer.
